//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPATIENT()
        {
            this.TBLSESSION = new HashSet<TBLSESSION>();
        }
    
        public int PATIENTID { get; set; }
        public string PATIENTNAME { get; set; }
        public string PATIENTSURNAME { get; set; }
        public Nullable<short> PATIENTAGE { get; set; }
        public string PATIENTGENDER { get; set; }
        public int PATIENTEHA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSESSION> TBLSESSION { get; set; }
    }
}
