//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSESSION
    {
        public int ID { get; set; }
        public Nullable<short> ExID { get; set; }
        public Nullable<int> PatID { get; set; }
        public Nullable<int> DURATION { get; set; }
        public int VELOCITY { get; set; }
        public int POSITION { get; set; }
    
        public virtual TBLEXERCISE TBLEXERCISE { get; set; }
        public virtual TBLPATIENT TBLPATIENT { get; set; }
    }
}
