//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEXERCISE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLEXERCISE()
        {
            this.TBLSESSION = new HashSet<TBLSESSION>();
        }
    
        public short EXERCISEID { get; set; }
        public string EXERCISENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSESSION> TBLSESSION { get; set; }
    }
}
